# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='机房座机电话'),
        ),
    ]
