# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_serverauto'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Idc', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_auto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.ServerAuto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='server_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ServerUser', verbose_name='管理用户'),
        ),
    ]
