# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20190925_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_auto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.ServerAuto', verbose_name='推送客户端关联'),
        ),
    ]
