# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('resources', '0007_auto_20190927_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='业务线'),
        ),
    ]
